import SBILeanProject.GR.RefinedGroupedReport
import Lean.Elab.Command

set_option autoImplicit false

open Lean Elab Command

namespace GRGroupedMapColor

/-!
Color styling for the human-facing GR grouped dependency map.

The dependency structure itself is generated by `GR.RefinedGroupedReport`.
This module changes only the GraphML presentation, preserving every node,
group assignment and machine-derived dependency edge.

The palette follows the convention used in the companion formalization maps:

  * orange   -- interfaces imported from our own companion formal structures;
                these ultimately rest on the axiomatic SBI development;
  * yellow   -- definitions / external theorem interfaces supplied as inputs;
  * lavender -- intermediate definitions, semantic bridges and derived results;
  * green    -- principal manuscript-level theorems / structural conclusions.

The node shapes generated by the grouped report are retained.  Color and shape
therefore carry complementary information.
-/

/-- Companion-formalization interfaces imported into the GR argument. -/
def orangeGroupIds : List String := [
  "constraint-capacity",
  "causal-duration"
]

/-- Definitions and external theorem interfaces supplied as inputs. -/
def yellowGroupIds : List String := [
  "lorentz-classification",
  "effective-manifold",
  "metric-closure",
  "local-conservation",
  "effective-source",
  "lovelock-interface"
]

/-- Principal section-level or manuscript-level conclusions. -/
def greenGroupIds : List String := [
  "reachability-domain",
  "kinematics-conclusion",
  "einstein-synthesis",
  "effective-gr-conclusion"
]

/-- Pastel colors matching the established manuscript-map palette. -/
def orangeFill : String := "#FFCC99"
def yellowFill : String := "#FFFF99"
def lavenderFill : String := "#CCCCFF"
def greenFill : String := "#CCFFCC"

/-- Detect a literal substring without depending on parser-oriented string APIs. -/
def hasLiteral (line needle : String) : Bool :=
  line.replace needle "" != line

/-- True when one GraphML node line belongs to the supplied conceptual group. -/
def lineHasGroupId (line id : String) : Bool :=
  hasLiteral line ("<data key=\"d0\">" ++ id ++ "</data>")

/-- Choose the grouped-map fill color from its manuscript role. -/
def fillForGroupLine (line : String) : String :=
  if orangeGroupIds.any fun id => lineHasGroupId line id then
    orangeFill
  else if yellowGroupIds.any fun id => lineHasGroupId line id then
    yellowFill
  else if greenGroupIds.any fun id => lineHasGroupId line id then
    greenFill
  else
    lavenderFill

/-- Insert a yEd fill element into one generated grouped-map node. -/
def styleGroupedNodeLine (line : String) : String :=
  if hasLiteral line "<node id=\"g" then
    let fill := fillForGroupLine line
    line.replace
      "<y:ShapeNode>"
      ("<y:ShapeNode><y:Fill color=\"" ++ fill ++
        "\" transparent=\"false\"/>")
  else
    line

/-- Apply the manuscript palette to the generated grouped GraphML file. -/
def styleGroupedGraphml (text : String) : String :=
  String.intercalate "\n" ((text.splitOn "\n").map styleGroupedNodeLine)

syntax (name := styleGRGroupedMapCmd) "#style_gr_grouped_map" : command

@[command_elab styleGRGroupedMapCmd]
def elabStyleGRGroupedMap : CommandElab := fun _ => do
  let path := "gr-grouped-map.graphml"
  let raw ← liftIO <| IO.FS.readFile path
  liftIO <| IO.FS.writeFile path (styleGroupedGraphml raw)
  logInfo m!"Styled refined GR grouped map written to {path}: orange = imported companion interfaces, yellow = imported/input definitions, lavender = intermediate structure, green = principal theorems."

end GRGroupedMapColor

#style_gr_grouped_map
